sudo: required
dist: trusty
language: csharp
solution: src/noised.sln
install:
      - nuget restore src/noised.sln
      - nuget install NUnit.Runners -Version 2.6.4 -OutputDirectory testrunner
script:
      - xbuild /nologo /p:DefineConstants="UNIX" /p:UNIX=TRUE /p:Configuration=Release /property:GenerateFullPaths=true src/noised.sln
      - mono ./testrunner/NUnit.Runners.2.6.4/tools/nunit-console.exe ./src/NoisedTests/bin/Release/NoisedTests.dll
notifications:
    email:
        recipients:
            - bennygr@gmx.net
            - sebingel+noised@googlemail.com
        on_success: change # default: change
        on_failure: always # default: always
addons:
    apt:
        packages:
            - libgstreamer1.0-dev 
